---
language: ruby
sudo: false
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
script: bundle exec rake test
env:
  - PUPPET_GEM_VERSION="~> 4.10.0"
rvm:
  - 2.2
