---
language: ruby
sudo: false
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
# NOTE: for now, we can only run syntax + spec as lint and validate will throw
#       warning/errors.
#       Same for STRICT_VARIABLES: should be removed to run on Puppet4 defaults
script: STRICT_VARIABLES=no bundle exec rake syntax spec_prep spec_standalone
# TODO switch on this travis command at then end:
#script: STRICT_VARIABLES=no bundle exec rake test
# TODO unset STRICT_VARIABLES to be compatible with Puppet4 defaults
#script: bundle exec rake test
env:
  - PUPPET_GEM_VERSION="~> 4.10.0"
rvm:
  - 2.2
